// SPDX-License-Identifier: GPL-2.0-or-later
//
// Zeus — OpenHPSDR Protocol-1 / Protocol-2 client.
//
// On-disk SSTV gallery: one PNG per received picture plus a JSON sidecar with
// its metadata, both named by a stable key
//     20260925-213012Z_14233kHz_Martin1
// Plain files on purpose (not LiteDB): operators want to open, copy and post
// their pictures, and a PNG in a folder is the format every tool already
// speaks. The PNG also carries the metadata as tEXt so a picture copied out
// of the folder still says what it is.
//
// The directory is PrefsDbPath.SstvDir() — next to the active prefs file, so
// `ZEUS_PREFS_PATH` (dev `/run fresh`, CI) isolates it. All I/O is
// best-effort: a full disk or a read-only folder must never take the decoder
// down, so failures are logged by the caller and the picture simply stays
// session-only.

using System.Globalization;
using System.Text.Json;

namespace Zeus.Server.Hosting.Digital.Sstv;

public sealed record SstvStoredMeta(
    string Key,
    string Mode,
    int Width,
    int Height,
    int RowsDone,
    double OffsetHz,
    double ClockErrorPpm,
    long DialHz,
    string SideBand,
    long StartedUnixMs,
    long? EndedUnixMs,
    string? EndReason,
    double SlantPpm,
    double ShiftPx,
    string? Callsign);

public sealed class SstvGallery
{
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web) { WriteIndented = true };

    public SstvGallery(string dir) => Dir = dir;

    public string Dir { get; }

    public static string MakeKey(long startedUnixMs, long dialHz, string modeName)
    {
        var t = DateTimeOffset.FromUnixTimeMilliseconds(startedUnixMs).UtcDateTime;
        string mode = new string(modeName.Where(char.IsLetterOrDigit).ToArray());
        string freq = dialHz > 0 ? $"_{dialHz / 1000}kHz" : "";
        return $"{t:yyyyMMdd-HHmmss}Z{freq}_{mode}";
    }

    /// <summary>Write (or overwrite) a picture and its sidecar.</summary>
    public void Save(SstvStoredMeta meta, ReadOnlySpan<byte> rgb)
    {
        Directory.CreateDirectory(Dir);
        var png = PngWriter.EncodeRgb(rgb, meta.Width, meta.Height,
        [
            new("Software", "Zeus (OpenHPSDR)"),
            new("Title", $"SSTV {meta.Mode}"),
            new("Creation Time", DateTimeOffset.FromUnixTimeMilliseconds(meta.StartedUnixMs)
                .UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss 'UTC'", CultureInfo.InvariantCulture)),
            new("Comment", Describe(meta)),
        ]);
        // Write-then-rename so a crash mid-write never leaves a torn PNG that
        // the index would then list.
        WriteAtomic(PngPath(meta.Key), png);
        WriteAtomic(JsonPath(meta.Key), JsonSerializer.SerializeToUtf8Bytes(meta, Json));
    }

    /// <summary>Newest first, at most <paramref name="max"/>. Sidecars whose
    /// PNG is gone (deleted by hand) are skipped; unreadable ones too.</summary>
    public List<SstvStoredMeta> LoadIndex(int max)
    {
        var list = new List<SstvStoredMeta>();
        if (!Directory.Exists(Dir)) return list;
        foreach (var path in Directory.EnumerateFiles(Dir, "*.json"))
        {
            try
            {
                var m = JsonSerializer.Deserialize<SstvStoredMeta>(File.ReadAllBytes(path), Json);
                if (m is null || m.Key != Path.GetFileNameWithoutExtension(path)) continue;
                if (!File.Exists(PngPath(m.Key))) continue;
                list.Add(m);
            }
            catch (Exception ex) when (ex is IOException or JsonException or UnauthorizedAccessException)
            {
                /* skip a bad sidecar; never fail the whole index */
            }
        }
        list.Sort((a, b) => b.StartedUnixMs.CompareTo(a.StartedUnixMs));
        if (list.Count > max) list.RemoveRange(max, list.Count - max);
        return list;
    }

    public byte[]? ReadPng(string key)
    {
        var p = PngPath(key);
        return File.Exists(p) ? File.ReadAllBytes(p) : null;
    }

    public void Delete(string key)
    {
        File.Delete(PngPath(key));
        File.Delete(JsonPath(key));
    }

    private string PngPath(string key) => Path.Combine(Dir, SafeKey(key) + ".png");
    private string JsonPath(string key) => Path.Combine(Dir, SafeKey(key) + ".json");

    /// <summary>Keys are generated by <see cref="MakeKey"/>; reject anything
    /// else so a key can never walk out of the gallery directory.</summary>
    private static string SafeKey(string key)
    {
        if (key.Length == 0 || key.Any(c => !(char.IsLetterOrDigit(c) || c is '-' or '_')))
            throw new ArgumentException($"invalid gallery key '{key}'", nameof(key));
        return key;
    }

    private static void WriteAtomic(string path, byte[] bytes)
    {
        var tmp = path + ".tmp";
        File.WriteAllBytes(tmp, bytes);
        File.Move(tmp, path, overwrite: true);
    }

    private static string Describe(SstvStoredMeta m)
    {
        var parts = new List<string> { m.Mode };
        if (m.DialHz > 0)
            parts.Add(string.Create(CultureInfo.InvariantCulture, $"{m.DialHz / 1e6:0.000} MHz {m.SideBand}"));
        if (!string.IsNullOrEmpty(m.Callsign)) parts.Add($"de {m.Callsign}");
        return string.Join(", ", parts);
    }
}
